### ISSUE TITLE
MEMO

### ISSUE THREAD

**Issue by sjbworks** [sjbworks/nekomi-analytics#1]
# TODO
- [x] Fix where image import could not be resolved
- [x] Apply Tailwind CSS
  - [x] Resolve the following
    - [x] Unknown rule declaration-block-no-duplicate-custom-properties.
    - [x] Unknown rule named-grid-areas-no-invalid.
- [x] Create Meter Analytics page
  - [x] Decide on a graph library -> apexcharts
  - [x] Create LineChart component
    - [x] create empty LineChart
    - [x] add option
  - [x] Adjust LineChart
    - [x] format yAxis value
  - [x] Introduce Storybook 
  - [x] Create mock
- [x] Create Core fan Analytics page
- [ ] Create Registration page
- [ ] Introduce backend
  - [ ] firebase? make your own?
